### ISSUE TITLE
PL-23 ⁃ Use better "production" domainname

### ISSUE THREAD

**Issue by ayanozturk** [comicrelief/pattern-lab#104]
- Decide on a new domain name. https://pattern-lab.comicrelief.com ?
- Configure SSL and CI to use the new domain for deployments.

**Comment by pvhee** [comment]
@aaomoware could we set up this domain name to use for the pattern lab?

**Comment by adamclark-dev** [comment]
Duplicated by ticket https://github.com/comicrelief/pattern-lab/issues/678

**Comment by CRSync** [comment]
➤ Unito Sync commented:

Transition made by Unito
