### ISSUE TITLE
SVG - Cookies close button issue

### ISSUE THREAD

**Issue by pradip3271** [comicrelief/pattern-lab#165]
In mobile and tab devices, 'X' mark missing in cookies close button. See attachment.
![cookieclosebtn](https://user-images.githubusercontent.com/20820603/27905901-5d45ec32-6239-11e7-8aa7-371dad095c99.png)

**Comment by Heleen-cr** [comment]
@pradip3271 this can be re-QA'd 
https://deploy-preview-188--cr-pattern-lab.netlify.com/section-20.html#kss-fullscreen-kssref-20-115
https://deploy-preview-188--cr-pattern-lab.netlify.com/cr/section-20.html#kss-fullscreen-kssref-20-115

**Comment by Heleen-cr** [comment]
Specific comicrelief test environment: https://github.com/comicrelief/comicrelief/pull/161

**Comment by Heleen-cr** [comment]
@pradip3271 This issue can be QA'd again
http://pr-161-vzh3n6y-bvhi5i64rjmnk.eu.platform.sh/

**Comment by pradip3271** [comment]
@Heleen-cr Passed QA, Ready to merge.
