### ISSUE TITLE
PL-25 ⁃ Pattern Headings

### ISSUE THREAD

**Issue by gusliedke** [comicrelief/pattern-lab#228]
https://tympanus.net/Tutorials/TexturedText/index2.html

![worn](https://user-images.githubusercontent.com/1434022/28927095-8a66e2be-7861-11e7-9a25-9b28700a8252.png)
<img width="650" alt="screen shot 2017-08-02 at 15 01 02" src="https://user-images.githubusercontent.com/1434022/28927096-8a88ef4e-7861-11e7-93b3-709ab66dfd87.png">

**Comment by gusliedke** [comment]
Prototype it in CR. It could be a media entity display. fields img and title and deal with the title pattern in the display template.

**Comment by AndyEPhipps** [comment]
@jeffaddeh @dan-ridge: are we still hoping to go ahead with this or not?

**Comment by dan-ridge** [comment]
@AndyEPhipps not at present, might be something to consider at a later date but currently not a priority.

**Comment by CRSync** [comment]
➤ Unito Sync commented:

Transition made by Unito
