### ISSUE TITLE
PL-27 ⁃ Fix social following icons

### ISSUE THREAD

**Issue by Heleen-cr** [comicrelief/pattern-lab#230]
The instagram and Google+ SVGs in the spritesheet seem to be wrong. 
Also some icons don't have the correct link.

The social following icons are used in the footer component. At the moment we're overriding these icons in each drupal theme.

**Comment by Heleen-cr** [comment]
if this is critical it will be raised when we're creating the new cr footer.

**Comment by CRSync** [comment]
➤ Unito Sync commented:

Transition made by Unito
