### ISSUE TITLE
Content wall text formatting updates for SR18 website

### ISSUE THREAD

**Issue by CarolineRennie** [comicrelief/pattern-lab#231]
The content wall component currently always displays text as centred.
For the new Sport Relief look and feel, there is a requirement for the text to be left or right aligned:

![image](https://user-images.githubusercontent.com/23260070/29024341-90739a48-7b69-11e7-9fd0-5e82b0561718.png)

Please can we add this as an option for content editors to control the alignment formatting on the content wall?

As a rule, the default should be centred.

**Comment by gusliedke** [comment]
Currently we have [CW Large teaser block](https://pattern-lab-systest.apps.comicrelief.com/section-20.html#kssref-20-20) with body copy left text centred aligned. We can add a new view mode (CW L left and CW L right) to layout copy right and left and remove centred alignment to be controlled via ckeditor

**Comment by gusliedke** [comment]
Ok, I will remove the text alignment to be controlled via ckeditor. The new view mode will be in a new ticket if required.
