### ISSUE TITLE
PL-28 ⁃ 'Tag' class to remove padding from text 

### ISSUE THREAD

**Issue by CarolineRennie** [comicrelief/pattern-lab#238]
Jeff to try style in browser - Tag as subtitle / associated text - tag could be above or below the main content:

![image](https://user-images.githubusercontent.com/23260070/29124627-56557418-7d11-11e7-8314-f6d80c7242be.png)

![image](https://user-images.githubusercontent.com/23260070/29124580-35dd79ba-7d11-11e7-91f8-203990d63c66.png)

**Comment by CRSync** [comment]
➤ Unito Sync commented:

Transition made by Unito
