### ISSUE TITLE
PL-29 ⁃ Create mobile styling for bullet points

### ISSUE THREAD

**Issue by CarolineRennie** [comicrelief/pattern-lab#239]
Default rules for colour required.

Mobile styling for bullet points.

Spacing between bullet points and multi-level bullet points.

![image](https://user-images.githubusercontent.com/23260070/29125127-d1139dfa-7d12-11e7-88f6-22e7fbe884ee.png)

**Comment by Heleen-cr** [comment]
been open for over a year.. we'll see if it comes up in the redesign.

**Comment by CRSync** [comment]
➤ Unito Sync commented:

Transition made by Unito
