### ISSUE TITLE
Reduce padding to 15px from inside cards when the background colour is set to ‘No colour’

### ISSUE THREAD

**Issue by CarolineRennie** [comicrelief/pattern-lab#242]
With no colour background, card rows of 4 should have reduced padding for the text to only be 15px -the columns are too narrow with too much space in-between so from this:

![image](https://user-images.githubusercontent.com/23260070/29126628-cdcb397e-7d16-11e7-8a50-2e13e8d4f245.png)

To this:

![image](https://user-images.githubusercontent.com/23260070/29126414-3750d990-7d16-11e7-9c7e-d9bec6a15236.png)

**Comment by Heleen-cr** [comment]
http://pr-54-krqdrhi-wf5gj4v6kiu2o.eu.platform.sh/get-involved
@JamesSquire could you have a look at the cards padding and tell me if this is ok?

**Comment by Heleen-cr** [comment]
top and bottom padding should be 30px, but left and right no padding
