### ISSUE TITLE
Review image crop on background Single Message 

### ISSUE THREAD

**Issue by CarolineRennie** [comicrelief/pattern-lab#250]
Currently the image is cropped down to 450px and displays it up to 500px - the design team are cropping the assets to display as 500px and are losing 50px in the crop when the image has been uploaded to the CMS. 

For example:
ORIGINAL IMAGE:
![image](https://user-images.githubusercontent.com/23260070/29273411-12cf68ae-80fc-11e7-9bcb-09ae0581442c.png)

HOW IT DISPLAYS ON SITE (go to bottom):
![image](https://user-images.githubusercontent.com/23260070/29273456-3f288af2-80fc-11e7-935a-2524c06b01ca.png)

**Comment by Heleen-cr** [comment]
created an issue to update the image styles in campaign:
https://github.com/comicrelief/campaign/issues/1173
