### ISSUE TITLE
PL-30 ⁃ Default white or black text depending on colour background from header

### ISSUE THREAD

**Issue by CarolineRennie** [comicrelief/pattern-lab#252]
When background colours are displayed (on mobile/tablet) the copy should follow the rules for button colours e.g. if dark purple then text is white or if white then black.

![image](https://user-images.githubusercontent.com/23260070/29274901-49f54042-8101-11e7-9459-89d029b45fbc.png)

**Comment by Heleen-cr** [comment]
open for over a year, so most likely fixed or if still an issue we'll notice with the redesign.

**Comment by CRSync** [comment]
➤ Unito Sync commented:

Transition made by Unito
