### ISSUE TITLE
Vertically align select box options

### ISSUE THREAD

**Issue by dan-ridge** [comicrelief/pattern-lab#284]
Select box options need to be vertically aligned inside the field, only a few pixels out. Raised by shop but needs to be fixed in pattern lab. Spoke to @AndyEPhipps about this

![screen shot 2017-09-06 at 11 33 12](https://user-images.githubusercontent.com/31690034/30205579-1c8993d6-9481-11e7-9093-21164aef5612.png)

**Comment by Heleen-cr** [comment]
@dan-ridge this fix needs to be done by MRM. I've created a ticket in Jira for this (SHOP-108)

**Comment by Heleen-cr** [comment]
actually, as the main issue here is the font itself, I will re-download the Sailec-regular font and add it to the shop theme.
