### ISSUE TITLE
font updates SR18

### ISSUE THREAD

**Issue by Heleen-cr** [comicrelief/pattern-lab#299]
- H1  uppercase + condensed bold font 
- H2  uppercase + letter spacing + semibold font
- H3 to H5 semibold font  
- H3.alternate uppercase + letter spacing + semibold font
- update font sizes (see google sheet)

**Comment by Heleen-cr** [comment]
@jeffaddeh here's an example of an issue, now you can follow its progress ;)

**Comment by Heleen-cr** [comment]
test environment here: http://pr-37-icdxs2a-wf5gj4v6kiu2o.eu.platform.sh/

**Comment by jeffaddeh** [comment]
**DESKTOP** 
_Size / Line Height_
H1.large - 167px / 125px
H1 - 117px / 88px

**TABLET**
_Size / Line Height_
H1.large - 132px / 99px
H1 - 92px / 69px

**MOBILE**
_Size / Line Height_
H1.large - 65px / 49px
H1 - 58px / 43px
