### ISSUE TITLE
SR18 button updates

### ISSUE THREAD

**Issue by AndyEPhipps** [comicrelief/pattern-lab#306]
@jeffaddeh to add deets

**Comment by jeffaddeh** [comment]
- Square buttons
- Text: Uppercase, 0.1em letter-spacing
- Padding: 30px (left/right)
- Font size: 18px
- Button height: 60px height
- Border (for ghost buttons): 1px border
- Hover states to still be worked on

**Comment by jeffaddeh** [comment]
Also links!

**Links**
  - Sentence case
  - Font family/weight: Founders Grotesk Semibold
  - Underline/border: 1px
  - Colour: Copy and underline match the same colour (colour to be confirmed)
  
**Inline Links**
  - Sentence case
  - Font family/weight: Inherit from paragraph
  - Underline/border: 1px
  - Colour: Copy uses lead colour (colour to be confirmed), underline is grey/transparent colour?

**Comment by AndyEPhipps** [comment]
@jeffaddeh: gonna make the above a separate issue
