### ISSUE TITLE
SR18 links update

### ISSUE THREAD

**Issue by AndyEPhipps** [comicrelief/pattern-lab#307]
**Links**

Sentence case
Font family/weight: Founders Grotesk Semibold
Underline/border: 1px
Colour: Copy and underline match the same colour (colour to be confirmed)
Inline Links

Sentence case
Font family/weight: Inherit from paragraph
Underline/border: 1px
Colour: Copy uses lead colour (colour to be confirmed), underline is grey/transparent colour?

Examples here:

![68747470733a2f2f64326d787565667165616137736a2e636c6f756466726f6e742e6e65742f735f333034333131433841313744423338363631344446374337383837414246443843393435444543464342353535314530324532324637453638444231424242335f313530353431313636363031335f69](https://user-images.githubusercontent.com/4737220/30642980-07ad23c8-9e05-11e7-9bba-0169c346dc10.png)

**Comment by AndyEPhipps** [comment]
Assigning to everyone so it's on all of our radars

**Comment by Heleen-cr** [comment]
@jeffaddeh preview here: 
http://pr-101-cyj2yty-mw3yu47main2e.eu.platform.sh/
http://pr-101-cyj2yty-mw3yu47main2e.eu.platform.sh/what-is-sport-relief

**Comment by Heleen-cr** [comment]
### test notes
- go to http://pr-101-cyj2yty-mw3yu47main2e.eu.platform.sh/what-is-sport-relief
- log in and edit a page
- when you add a link, you should see default link styling 
 ** dark-blue-lighter colour (`#223c59`)with a line underneath when the link is surrounded by p tags
 ** dark-blue colour (`#061d38`) when it's surround by h1 - h5 tags
 ** the link should inherit the font-family and font-size of the tags surrounding it.
- Test changing the colour and type of link using the styles dropdown
-  note: the image above is not up to date. The inline link has the same colour underlining as the link text itself.
- on hover the line underneath disappears (becomes transparent).

**Comment by pradip3271** [comment]
Passed QA, ready to merge.
