### ISSUE TITLE
Bug sr18 inline link underlining

### ISSUE THREAD

**Issue by Heleen-cr** [comicrelief/pattern-lab#348]
Inline links on sr18 have `display: inline-block` on them which makes the border go full width rather than staying underneath the actual text of the link
<img width="249" alt="screen shot 2017-10-06 at 15 33 15" src="https://user-images.githubusercontent.com/21171954/31284609-f91b6690-aab0-11e7-9c6c-d4a2bb196682.png">

- Remove `display: inline-block` from inline links and give it `padding-bottom: 0.06em`

**Comment by Heleen-cr** [comment]
### test notes
- go to: http://pr-132-py5r3ka-mw3yu47main2e.eu.platform.sh/about-sport-relief
- log in
- edit a card that has limited with (like one of the 1/4 width ones) 
- add an inline link that stretches over multiple lines
- the underlining of the link should remain underneath the link's text and not stretch wider. 
- there should be a small padding between the link's text the line underneath (0.06em)

**Comment by Heleen-cr** [comment]
@JamesSquire link fix: http://pr-132-py5r3ka-mw3yu47main2e.eu.platform.sh/about-sport-relief

**Comment by pradip3271** [comment]
Passed QA, ready to merge.
