### ISSUE TITLE
PL-39 ⁃ Update teaser block to inherit bg-color classes 

### ISSUE THREAD

**Issue by AndyEPhipps** [comicrelief/pattern-lab#381]
.teaser-block--bg-image {
  .teaser-block__body {
     position: absolute;
     top: 0;
     left: 0;
     width: calc(100% - 10 * 1.25%);
     height: 100%;
     margin: 0 calc(5 * 1.25%);
     **background-color: transparent;** << the issue
}

![screen shot 2017-11-10 at 11 37 30](https://user-images.githubusercontent.com/4737220/32657045-23042cdc-c60c-11e7-8c23-65dd91611aac.png)
**What we have - _bad_**

![screen shot 2017-11-10 at 11 37 39](https://user-images.githubusercontent.com/4737220/32657048-298961ee-c60c-11e7-9735-22ac6553fef5.png)
**What we want - _ugly but functionally correct_**

**Comment by CRSync** [comment]
➤ Unito Sync commented:

Transition made by Unito
