### ISSUE TITLE
PL-18 ⁃ Implement prepopulated field/Apple Pay-related style updates to Donate theme work

### ISSUE THREAD

**Issue by AndyEPhipps** [comicrelief/pattern-lab#394]
Covered by main ticket https://github.com/comicrelief/donate/issues/37

Related to BE work:
https://github.com/comicrelief/donate/issues/38
https://github.com/comicrelief/donate/issues/30

**Comment by CRSync** [comment]
➤ Unito Sync commented:

Transition made by Unito
