### ISSUE TITLE
PL-42 ⁃ Updated Teaser Block (& poss. others) template to include cr-body wrapper to match Drupal

### ISSUE THREAD

**Issue by AndyEPhipps** [comicrelief/pattern-lab#400]

**Comment by AndyEPhipps** [comment]
Have updated Teaser Blocks as part of https://github.com/comicrelief/pattern-lab/issues/428; will close this for now and we can fix as any other issues arise (fyi @Heleen-cr )

**Comment by CRSync** [comment]
➤ Unito Sync commented:

Transition made by Unito
