### ISSUE TITLE
PL-43 ⁃ Set site default OG image as news articles with no image default

### ISSUE THREAD

**Issue by CarolineRennie** [comicrelief/pattern-lab#401]
For articles with no relevant image, we need a default image which is relevant to the website that the news article is published on.

Currently there is a default image set across all sites which has to be manually overridden in each site - it would be better if this image inherited the default OG image of the site rather than pulling through the current image as default:

![image](https://user-images.githubusercontent.com/23260070/33660699-ac69651c-da7c-11e7-8ee9-87011ebc3477.png)

**Comment by AndyEPhipps** [comment]
Not sure if this is still required or not, but this would need to be raised in CR.com
