### ISSUE TITLE
PL-48 ⁃ Donate: add promo header styling

### ISSUE THREAD

**Issue by Heleen-cr** [comicrelief/pattern-lab#418]
subtask of https://github.com/comicrelief/donate/issues/37

- also solve the height issue for mobile

<img width="681" alt="screen shot 2018-01-03 at 16 04 41" src="https://user-images.githubusercontent.com/21171954/34528143-df81c172-f09f-11e7-8560-cc1cfdbcc112.png">

**Comment by CRSync** [comment]
➤ Unito Sync commented:

Transition made by Unito
