### ISSUE TITLE
PL-51 ⁃ Donate - content section styling

### ISSUE THREAD

**Issue by Heleen-cr** [comicrelief/pattern-lab#426]
- hide payment details row and remove currency selector from twig
- implement the styling for show and hide giftaid row
- centre content
- update colours
- add card logos and show logo row
subtask of https://github.com/comicrelief/donate/issues/37
  
  
<img width="422" alt="screen shot 2018-01-04 at 12 54 05" src="https://user-images.githubusercontent.com/21171954/34564378-66a19d5e-f14e-11e7-955a-49caf2d671e0.png">
<img width="181" alt="screen shot 2018-01-04 at 12 57 44" src="https://user-images.githubusercontent.com/21171954/34564538-f3369ff8-f14e-11e7-8321-56fecaf25905.png">

<img width="187" alt="screen shot 2018-01-04 at 12 54 53" src="https://user-images.githubusercontent.com/21171954/34564400-7e16222a-f14e-11e7-9663-e98a40e78fbb.png">

**Comment by CRSync** [comment]
➤ Unito Sync commented:

Transition made by Unito
