### ISSUE TITLE
PL-53 ⁃ Donate - thankyou page styling

### ISSUE THREAD

**Issue by Heleen-cr** [comicrelief/pattern-lab#430]
related to https://github.com/comicrelief/donate/issues/105
subtask of: https://github.com/comicrelief/donate/issues/37

<img width="291" alt="screen shot 2018-01-04 at 12 52 33" src="https://user-images.githubusercontent.com/21171954/34564331-2b3c4c82-f14e-11e7-843c-71aeb9722fe3.png">

**Comment by Heleen-cr** [comment]
exported this from sketch... not sure if the quality will be good enough
![default](https://user-images.githubusercontent.com/21171954/34716337-75185eb8-f527-11e7-85c4-19aa0d7f90ad.png)

**Comment by CarolineRennie** [comment]
Copy:
You have donated £[amount]
Thank you!
[BIG THUMBS UP]
Your money will help fund incredible projects in the UK and around the world, tackling vital social issues.

**Comment by CRSync** [comment]
➤ Unito Sync commented:

Transition made by Unito
