### ISSUE TITLE
PL-62 ⁃ Move stylesheets from Payin to Pay-In SR subtheme

### ISSUE THREAD

**Issue by CarolineRennie** [comicrelief/pattern-lab#449]
- Copy default payin stuff to new default folder 
(keep components folder containing images. Otherwise donate will have image problems... delete later when the paths are updated in donate, see https://github.com/comicrelief/donate/issues/158)
- create separate sportrelief folder
- update gruntfile with new paths
- update donate imports with correct payin paths 

Note: the payin subtheme in PL will show the payin-sportrelief subtheme

**Comment by CarolineRennie** [comment]
Subtask of not-37 https://github.com/comicrelief/payin/issues/181

**Comment by CRSync** [comment]
➤ Unito Sync commented:

Transition made by Unito
