### ISSUE TITLE
PL-63 ⁃ Payin promo header styling

### ISSUE THREAD

**Issue by CarolineRennie** [comicrelief/pattern-lab#450]
![image](https://user-images.githubusercontent.com/23260070/35157866-3ed5b1ee-fd2d-11e7-8c59-5e86513d1756.png)

White font, black background

**Comment by CarolineRennie** [comment]
https://github.com/comicrelief/payin/issues/181

**Comment by Heleen-cr** [comment]
preview environment here: https://payin-preview.cfapps.io/?site=SR

**Comment by CRSync** [comment]
➤ Unito Sync commented:

Transition made by Unito
