### ISSUE TITLE
PL-64 ⁃ Payin card row styling

### ISSUE THREAD

**Issue by CarolineRennie** [comicrelief/pattern-lab#451]
![image](https://user-images.githubusercontent.com/23260070/35157947-7147fc36-fd2d-11e7-9c20-20e7b0fbb2af.png)

Background - black
Check design for copy over image style
@JamesSquire can you add the assets for the audiences on this ticket please?

**Comment by CarolineRennie** [comment]
https://github.com/comicrelief/payin/issues/181

**Comment by JamesSquire** [comment]
![gyms 2x](https://user-images.githubusercontent.com/31689665/35326899-fcb363d0-00ef-11e8-83ec-fb28208d2133.jpg)
![myself 2x](https://user-images.githubusercontent.com/31689665/35326900-fcc591cc-00ef-11e8-9c26-19e37caa21a6.jpg)
![schools 2x](https://user-images.githubusercontent.com/31689665/35326901-fcd77df6-00ef-11e8-9feb-8df605ad3122.jpg)
![workplaces 2x](https://user-images.githubusercontent.com/31689665/35326903-fce9aeae-00ef-11e8-895b-eb3e4c9a790f.jpg)

**Comment by JamesSquire** [comment]
Assets above!

**Comment by Heleen-cr** [comment]
@CarolineRennie @JamesSquire 
I just realised that this is a cards row styled as the content wall teaser block. 
This means I won't be reusing our existing work (the whole reason I'm moving payin styling to Pattern Lab). 
Do we wan't to keep this design or redesign it as what cards rows look like :)

**Comment by CarolineRennie** [comment]
@Heleen-cr @JamesSquire  - we had early doors designs of how to hack cards to looking more like the jazzy fade effect - should we do that?

**Comment by Heleen-cr** [comment]
ah ok sure we can hack away 👍

**Comment by deniselashlley** [comment]
@CarolineRennie or @JamesSquire are these card supposed to be linkable and if so where do they go?

**Comment by Heleen-cr** [comment]
@deniselashlley they go to the next form step. eg. href='#payin-step-two'

**Comment by CRSync** [comment]
➤ Unito Sync commented:

Transition made by Unito
