### ISSUE TITLE
PL-65 ⁃ Payin form styling

### ISSUE THREAD

**Issue by CarolineRennie** [comicrelief/pattern-lab#452]
![image](https://user-images.githubusercontent.com/23260070/35158231-66504418-fd2e-11e7-944f-c450ee87ad42.png)

![payment-details](https://user-images.githubusercontent.com/21171954/35738064-96161766-0825-11e8-92c9-9fec45ac6c70.png)

- [x] Centred form style
- [x] Form title styling - pull through audience title in bold
- [x] Required fields update
- [x] Update search icon in postcode lookup to be separate button
- [x] checkbox styling
- [x] refactor default form styling from donate an payin forms to default payin form
- [x] accessibility tweaks
- [x] payment step form styling
- [x]  form error styling
- [x] button styling

**Comment by CarolineRennie** [comment]
https://github.com/comicrelief/payin/issues/181

**Comment by Heleen-cr** [comment]
QA'd in https://github.com/comicrelief/payin/pull/231

**Comment by CRSync** [comment]
➤ Unito Sync commented:

Transition made by Unito
