### ISSUE TITLE
PL-66 ⁃ Payment details section styling

### ISSUE THREAD

**Issue by CarolineRennie** [comicrelief/pattern-lab#453]
![image](https://user-images.githubusercontent.com/23260070/35159313-ba535a16-fd31-11e7-94ca-c99f57a9525c.png)

- [ ] Card or paypal buttons

**Comment by CarolineRennie** [comment]
https://github.com/comicrelief/payin/issues/181

**Comment by Heleen-cr** [comment]
tackling this in the form styling see https://github.com/comicrelief/pattern-lab/issues/452

**Comment by CRSync** [comment]
➤ Unito Sync commented:

Transition made by Unito
