### ISSUE TITLE
PL-68 ⁃ Payin thank you page styling

### ISSUE THREAD

**Issue by CarolineRennie** [comicrelief/pattern-lab#454]
![image](https://user-images.githubusercontent.com/23260070/35159939-aa34591c-fd33-11e7-864b-9abe28461f26.png)

Linked to https://github.com/comicrelief/payin/issues/181

**Comment by deniselashlley** [comment]
@CarolineRennie do we have any assets - for where the money goes... and fundraiser the gallery, also the urls to where they go to

**Comment by CarolineRennie** [comment]
Copy:

**Where your money goes**
Sport Relief uses the money you give to fund incredible projects, in the UK and around the world, that tackle important social issues and ensure people are
safe, happy and healthy.

Find out more / https://www.sportrelief.com/where-your-money-goes




**#teamsportrelief**
Show that you're part of a nation-wide team of awesome fundraisers, by sharing photos of your Sport Relief activites on instagram. 
Don't forget to tag us with #teamsportrelief!

See the team / https://www.instagram.com/explore/tags/teamsportrelief/

**Comment by CarolineRennie** [comment]
Link titles: 
'Where your money goes'
'Instagram Team Sport Relief'

**Comment by CRSync** [comment]
➤ Unito Sync commented:

Transition made by Unito
