### ISSUE TITLE
PL-69 ⁃ Payin failure page styling

### ISSUE THREAD

**Issue by CarolineRennie** [comicrelief/pattern-lab#456]
@JamesSquire  - can you provide design for payment failure page please? 

Doesn't need to be too jazzy.

https://github.com/comicrelief/payin/issues/181

**Comment by JamesSquire** [comment]
@CarolineRennie Do we have any copy or other requirements for this page? Or is it the equivalent of a 404 page...

**Comment by JamesSquire** [comment]
@CarolineRennie Bumpity bump.

**Comment by CarolineRennie** [comment]
Copy: 
Payment failed
Sorry, your payment has failed. Please try again [link to payin.sportrelief.com] to pay in your fundraising money.

If you continue to experience issues, please contact us [link to contact us].

**Comment by CarolineRennie** [comment]
@JamesSquire inspired?

**Comment by JamesSquire** [comment]
Very!

**Comment by JamesSquire** [comment]
![payment-failed_v2 2x](https://user-images.githubusercontent.com/31689665/35393991-72f81984-01de-11e8-8024-f76880720172.jpg)
![payment-failed_v1 2x](https://user-images.githubusercontent.com/31689665/35393992-7314348e-01de-11e8-84c4-02482c94a753.jpg)

**Comment by JamesSquire** [comment]
Essentially, one uses the header (and gradient) only, whereas the other breaks it up a little. The former is a little more modern and slick, but the latter is arguably more accessible. Happy with either but preference is probably "v2" (the former).

**Comment by CarolineRennie** [comment]
Can we have the gradient on the initial Payin page? It's got a black background whereas this is almost like we're having a party about their failed payment?!

Can they match each other? I think I like the more accessible one as it's easier to read - also as this is majority desktop users, the entire screen gradient is a bit much?

**Comment by JamesSquire** [comment]
I hear ya. Tried adding the gradient to the initial page but, with the images, it became a little too loud. Maybe, as it would be a sombre experience, it should match with the "black" (#030E1A). In which case, I agree, we should use the version that breaks the content up a bit - especially with the dark footer. See below!

**Comment by JamesSquire** [comment]
![payment-failed_v3 2x](https://user-images.githubusercontent.com/31689665/35397305-05a15284-01e7-11e8-89b2-5171ebdfdd1a.jpg)

**Comment by CRSync** [comment]
➤ Unito Sync commented:

Transition made by Unito
