### ISSUE TITLE
PL-112 ⁃ Just In Time notifications

### ISSUE THREAD

**Issue by LaBustaffa** [comicrelief/pattern-lab#557]
Part of GDPR requires that for each piece of information that we collect from users we explain why and how we're going to use it.

**Comment by LauretBi** [comment]
Examples of this from BBC: https://comicrelief.box.com/s/mlky49fqan2xk1o33yg2oiifcovl87wr
Our existing Master doc for forms validation: https://docs.google.com/spreadsheets/d/1bkW4n7oUKhViCpUyUuVxPfzvSfGuUvkr_1xbKnpQH1A/edit?usp=sharing

**Comment by LaBustaffa** [comment]
Finalised report here: https://comicrelief.box.com/s/l92hgscbiq9ekuc22qtsnui0yedatdlz
And mockups: https://comicrelief.box.com/s/uwm30o5er5n0f26z0mqnbcg87ccn7ebo

**Comment by LaBustaffa** [comment]
@deniselashlley I've updated the mockups with a couple minor changes:
- the arrow down becomes an arrow up when the div gets expanded
- changed the order of sentences on JIT - Donate from GP to reflect the order in other locations
- aligned the links on the examples from giving pages to follow the standard style for links in GP

**Comment by CarolineRennie** [comment]
dev ticket here: https://github.com/comicrelief/pattern-lab/issues/576 closing this issue as accidentally had duplicate (plus the dev ticket just has the final requirements on)

**Comment by CRSync** [comment]
➤ Unito Sync commented:

Transition made by Unito
