### ISSUE TITLE
PL-119 ⁃ CR.com nav height tweak

### ISSUE THREAD

**Issue by AndyEPhipps** [comicrelief/pattern-lab#574]
Just noticed that our header isn't quite big enough for the actual menu:

![screen shot 2018-04-09 at 15 55 42](https://user-images.githubusercontent.com/4737220/38505192-7f6346e8-3c0e-11e8-8fc6-22e41a2893cd.png)

**Comment by CRSync** [comment]
➤ Unito Sync commented:

Transition made by Unito
