### ISSUE TITLE
PL-122 ⁃ CR donate - fix paypal fallback button styling

### ISSUE THREAD

**Issue by Heleen-cr** [comicrelief/pattern-lab#579]
This still appears with 30px rounded corners.

<img width="268" alt="screen shot 2018-04-12 at 11 37 07" src="https://user-images.githubusercontent.com/21171954/38672665-bf3fd04e-3e46-11e8-9ad7-cce4768815fd.png">

**Comment by CRSync** [comment]
➤ Unito Sync commented:

Transition made by Unito
