### ISSUE TITLE
PL-134 ⁃ Improvements to red 'Donate' button for the visually impaired

### ISSUE THREAD

**Issue by adamthomsCR** [comicrelief/pattern-lab#607]
The red primary button has been flagged as a problem for those that are visually impaired.

Contrast checker shows that it already has a ratio
4.55:1. If we need to have 7:1, the concern is that would introduce desaturated colours and dilute the brand identity. 

Proposing that we can introduce some font styling, like a shadow behind the text to improve accessibility but maintain the brand red. 

For example, the following mockup adds:
- text-shadow: 0 2px 9px #B30033;
- text-shadow: 0 1px 1px #B30033;
https://puu.sh/AevDH/82479e015f.png

**Comment by adamthomsCR** [comment]
Update. The colour/intensity of the shadow would be dependant on the button colour. If we went ahead with how this looks, we'd need to teak the styling for each button: https://puu.sh/AexRz/b1fb6fee77.png

**Comment by deniselashlley** [comment]
@pradip3271  ready for testing https://donate-preview.cfapps.io/?site=CRDONATE

the red button has text shadowed applied now that all that has changed.

**Comment by LaBustaffa** [comment]
looks good to me :)

**Comment by pradip3271** [comment]
Passed QA, ready for release.

**Comment by CRSync** [comment]
➤ Unito Sync commented:

Transition made by Unito
