### ISSUE TITLE
PL-148 ⁃ New RND19 colours

### ISSUE THREAD

**Issue by CarolineRennie** [comicrelief/pattern-lab#637]
New colours for RND19 - @Heleen-cr putting into pattern lab now for review.

[CR_BASE_COLOUR_PALETTE_SPECS with RAL (1).pdf](https://github.com/comicrelief/pattern-lab/files/2075943/CR_BASE_COLOUR_PALETTE_SPECS.with.RAL.1.pdf)

**Comment by Heleen-cr** [comment]
Here's a preview link: 
https://deploy-preview-635--cr-pattern-lab.netlify.com/rnd/section-10.html

**Comment by AndyEPhipps** [comment]
I guess this can be closed @Heleen-cr ?

**Comment by Heleen-cr** [comment]
yes.
