### ISSUE TITLE
Make CI pipeline public

### ISSUE THREAD

**Issue by ayanozturk** [comicrelief/pattern-lab#65]
Currently, CI pipeline to build pattern-lab pull requests is private and integrated into another team.

**Comment by ayanozturk** [comment]
made Concourse CI pipeline available at https://ci.apps.comicrelief.com/teams/main/pipelines/pattern-lab

**Comment by pvhee** [comment]
Great work @ayanozturk - the UX is a little strange though (you still see action buttons like pause pipeline or restart, however when clicked you are redirected to the login page).

**Comment by pvhee** [comment]
@ayanozturk what's the work required to make a pipeline public? We're considering doing the same in https://github.com/comicrelief/grants-api-serverless/issues/17
