### ISSUE TITLE
PL-170 ⁃ New CR.com Fonts and Colours

### ISSUE THREAD

**Issue by CarolineRennie** [comicrelief/pattern-lab#693]
Please can we get a Pattern Lab PR and then apply it to staging on CR.com
Montserrat Extra Bold is the headline font and Hind is the text font.
The headline font can be used in either all caps or in upper and lower case. 

Comic Relief Red 
Pantone 185 
R229/G38/B49
C0/M94/Y79/K0
RAL3028 Colour

Comic Relief Orange 
Pantone 2026
R252/G123/B57
C0/M63/Y78/K0
RAL2003 Colour

Comic Relief Yellow 
Pantone 7548
R255/G199/B0
C0/M22/Y100/K0
RAL1018 Colour

Comic Relief Green
Pantone 376
R121/G172/B43
C60/M10/Y100/K0
RAL6018 Colour

Comic Relief Blue
Pantone 285
R42/G114/B183
C83/M50/Y0/K0
RAL5023 Colour

Comic Relief Magenta
Pantone 233
R198/G3/B124
C20/M100/Y3/K0
RAL4010 Colour

Comic Relief Purple
Pantone Med Purple
R120/G54/B140
C65/M90/Y0/K0
RAL4008 Colour

Comic Relief Light Blue
Pantone 2985
R94/G194/B234
C60/M2/Y4/K0
RAL5024 Colour

**Comment by CarolineRennie** [comment]
https://comicrelief.app.box.com/s/yk0pj3pjp6qm9xtif3srtbbv9vna8tey/file/308715004880 - this is the full style guide -  @AndyEPhipps when you're working on this can you let me know if there are any pre-set rules on font colour over each other - I recall there being some mechanic to make sure that copy has to be white / black depending on background colour to ensure we have accessible colour contrast. Also @Heleen-cr did some quick tests on some of the colours she may be able to share

**Comment by Heleen-cr** [comment]
well if you want the hex values to put in https://webaim.org/resources/contrastchecker/, you can use this converter: http://smartfocus-email-template.netlify.com/color-converter.html
