### ISSUE TITLE
PL-180 ⁃ New TURBOFOOTER for CR.com

### ISSUE THREAD

**Issue by AndyEPhipps** [comicrelief/pattern-lab#720]
Relates to https://github.com/comicrelief/comicrelief/issues/557 (and posssssssibly https://github.com/comicrelief/storybook/issues/236)

**Comment by CarolineRennie** [comment]
Agreement from meeting:
Each titled section is a block:
- for large displays the blocks present as 3 blocks per row
- for medium displays the blocks present as 2 blocks per row
- for small displays the blocks present as 1 block per row and links are rolled up into title

When block has 4 or more items in it then items display in 2 columns
When block is displaying columns and word/character count forces line-break, item is displayed over 2 lines - spacing of line-break vs new item should make this clear
